package poach3r.github.io;

import com.google.gson.annotations.SerializedName;
import poach3r.github.io.Commands.AbstractCommand;
import poach3r.github.io.Commands.SDHQ.Deals.GetDealsById;
import poach3r.github.io.Commands.SDHQ.Deals.GetDealsByName;
import poach3r.github.io.Commands.SDHQ.Review.GetReviewById;
import poach3r.github.io.Commands.SDHQ.Review.GetReviewByName;
import poach3r.github.io.Commands.SDHQ.Review.Search;

import java.util.ArrayList;
import java.util.List;

/**
 * Deserialized config.json generated by GSON
 * Contains all user-configurable options as well as all the available commands
 *
 * @author poacher
 */
public class Config {
    @SerializedName("botToken")
    private String botToken;
    @SerializedName("itadKey")
    private String itadKey;
    @SerializedName("reviewLinkOverride")
    private List<List<String>> reviewLinkOverride;
    @SerializedName("affiliates")
    private List<Affiliate> affiliates;
    private final List<AbstractCommand> commands;

    public Config() {
        commands = new ArrayList<>();
        commands.add(new GetDealsByName(this));
        commands.add(new GetDealsById(this));
        commands.add(new GetReviewByName(this));
        commands.add(new GetReviewById(this));
        commands.add(new Search(this));
    }

    String getBotToken() {
        return botToken;
    }

    public String getItadKey() {
        return itadKey;
    }

    public List<List<String>> getReviewLinkOverride() {
        return reviewLinkOverride;
    }

    public List<Affiliate> getAffiliates() {
        return affiliates;
    }

    public List<AbstractCommand> getCommands() {
        return commands;
    }

    public static class Affiliate {
        @SerializedName("name")
        private String name;
        @SerializedName("url")
        private String url;
        @SerializedName("suffix")
        private String suffix;
        private List<List<String>> overrides;

        public String getName() {
            return name;
        }

        public String getUrl() {
            return url;
        }

        public String getSuffix() {
            return suffix;
        }

        public List<List<String>> getOverrides() {
            return overrides;
        }
    }
}
